#!/usr/bin/env python3
"""
heldout_backtest.py

Part 4 / Phase 5 (Validation). Answers a question Part 3 left open: was
the three-way baseline/heuristic/principled comparison in
`src/backtest/backtest_adverse.py` contaminated by in-sample fitting?

Checked directly: `backtest_adverse.py`'s `run_generic_backtest` replays
EVERY mid-price step in the capture (`n_steps=2393`, i.e. the full ~240s
window) -- including the chronologically FIRST 70% of the data that
`ml_informedness_classifier.py` trained its GradientBoostingClassifier
on (`train_test_split.n_train=1661` of `n_labeled=2373` rows, see
`data/processed/ml_informedness_metrics.json`). The classifier's own
train/test metrics were correctly evaluated only on the held-out 30%,
but the *backtest* that reports the headline adverse-selection-cost
numbers was NOT restricted to that same held-out slice. That's a real
contamination risk worth checking honestly, not something to leave
implicit: even though `p_informed` scores fed into heuristic/principled
quoting are themselves produced by a model that only ever *trained* on
the first 70%, the backtest's fill decisions and PnL over that first 70%
are still influenced by a classifier that has effectively "seen" that
exact price path already (it's the data used to fit both the informedness
label's feature relationships AND -- indirectly, since kappa/A/sigma are
estimated from the WHOLE capture -- the underlying AS parameters). A
clean validation reruns the identical three-way comparison restricted
to ONLY the chronological test slice the classifier itself never
trained on.

Methodology:
  1. Rebuild the exact same feature frame + chronological 70/30 split
     `ml_informedness_classifier.py` used (same `build_feature_frame`
     args, read back from `ml_informedness_metrics.json`'s
     `feature_meta` so this script can't silently drift out of sync;
     same `train_frac`).
  2. Take `test_df["local_ts"].min()` / `.max()` as the held-out window
     boundaries -- the same test rows the classifier's own ROC-AUC /
     precision / recall were computed on.
  3. Re-run baseline / heuristic / principled quoting, restricted to
     book/trade events inside that window only, with FRESH inventory and
     cash reset to zero at the window start (this is now its own
     self-contained backtest, not a continuation of whatever inventory
     the maker happened to be carrying at the 70% mark) and the AS
     "clock" (t_elapsed feeding the T-t horizon term) also reset to zero
     at the window start -- i.e. treated as its own quoting session of
     length equal to the held-out span, not a continuation of the
     original 240s/T=240 session. This is a documented design choice:
     the alternative (keeping the original t0 so t_elapsed continues
     counting from the full capture's start) would make the AS
     inventory-widening term artificially small throughout the held-out
     window (since tau=T-t would already be small), which has nothing to
     do with what's being validated here (out-of-sample classifier use)
     and would confound the comparison. Resetting the clock isolates
     that.
  4. The p_informed(t) signal used by heuristic/principled inside this
     window is looked up from the SAME `ml_informedness_scores.csv` Part
     3 already produced -- legitimate to reuse as-is, because those
     scores were generated by scoring (not re-fitting) a model that was
     ONLY EVER FIT on the training rows; scoring the test rows afterward
     is ordinary out-of-sample inference, not leakage.
  5. Report the same headline numbers Part 3 reported (total AND
     per-fill adverse-selection cost), plus inventory variance and
     realized spread captured (defined below), so the held-out numbers
     are directly comparable to Part 3's full-window numbers.

Realized spread captured (new metric, not in Part 3): for each fill,
the IMMEDIATE markup relative to the prevailing mid at the instant of
execution, ignoring what happens afterward:

    bid fill: captured = mid_at_fill - bid_price   (bought under mid)
    ask fill: captured = ask_price - mid_at_fill   (sold above mid)

This is the natural complement to adverse-selection cost: adverse-
selection cost is what the quoted spread gives BACK to informed flow
over the next horizon_sec; realized spread captured is what the quoted
spread earns UP FRONT at the moment of the trade. Net edge per fill =
realized_spread_captured_per_fill - adverse_selection_cost_per_fill.

Usage:
    python src/validation/heldout_backtest.py \
        --depth data/raw/depth_btcusdt_20260723_094653.jsonl \
        --trades data/raw/trades_btcusdt_20260723_094653.jsonl \
        --params-json data/processed/estimated_params.json \
        --scores-csv data/processed/ml_informedness_scores.csv \
        --ml-metrics-json data/processed/ml_informedness_metrics.json \
        --out-dir data/processed
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from bisect import bisect_left, bisect_right

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from src.backtest.backtest_adverse import (  # noqa: E402
    baseline_quote_fn,
    compute_adverse_selection_cost,
    load_p_informed_series,
    make_causal_lookup,
)
from src.model.avellaneda_stoikov import ASParams  # noqa: E402
from src.model.avellaneda_stoikov_adverse import (  # noqa: E402
    AdverseParams,
    heuristic_quotes,
    principled_quotes,
)
from src.model.estimate_params import load_mid_series, load_trades  # noqa: E402
from src.model.informedness_signal import build_feature_frame  # noqa: E402
from src.model.ml_informedness_classifier import chronological_split  # noqa: E402


def get_heldout_window(depth_path: str, trades_path: str, feat_meta: dict, train_frac: float):
    """Rebuild the identical feature frame + chronological split the
    classifier trained on, and return (test_start_ts, test_end_ts,
    n_test_rows) -- the exact held-out boundaries."""
    frame, meta = build_feature_frame(
        depth_path, trades_path,
        trailing_window_sec=feat_meta["trailing_window_sec"],
        horizon_sec=feat_meta["horizon_sec"],
        k_sigma=feat_meta["k_sigma"],
    )
    train_df, test_df = chronological_split(frame, train_frac)
    return (
        float(test_df["local_ts"].min()),
        float(test_df["local_ts"].max()),
        len(test_df),
        len(train_df),
    )


def run_windowed_backtest(depth_path: str, trades_path: str, horizon_T: float,
                           quote_fn, quote_params, window_start_ts: float,
                           window_end_ts: float, p_lookup=None, label: str = "run"):
    """Same fill/PnL mechanics as `backtest_adverse.run_generic_backtest`,
    but restricted to book/trade events with local_ts in
    [window_start_ts, window_end_ts], with inventory/cash reset to zero
    and the AS horizon clock (t_elapsed) restarted at window_start_ts --
    see module docstring for why. Fills additionally record the
    prevailing mid at execution (`mid`), so realized-spread-captured can
    be computed without a second lookup pass."""
    all_times, all_mids = load_mid_series(depth_path)
    all_trades = load_trades(trades_path)

    lo = bisect_left(all_times, window_start_ts)
    hi = bisect_right(all_times, window_end_ts)
    times = all_times[lo:hi]
    mids = all_mids[lo:hi]
    if len(mids) < 2:
        raise ValueError("Not enough mid-price observations in the held-out window")

    trades = [tr for tr in all_trades if times[0] <= tr["ts"] <= times[-1]]
    trades_sorted = sorted(trades, key=lambda tr: tr["ts"])
    tr_idx = 0
    n_trades = len(trades_sorted)

    t0 = times[0]
    q = 0.0
    cash = 0.0
    rows = []
    fills = []
    n_bid_fills = 0
    n_ask_fills = 0

    for i in range(len(mids) - 1):
        step_start = times[i]
        step_end = times[i + 1]
        s = mids[i]
        t_elapsed = min(step_start - t0, horizon_T)
        p_informed = p_lookup(step_start) if p_lookup is not None else 0.0

        bid, ask, r, spread = quote_fn(s, q, t_elapsed, p_informed, quote_params)

        bid_filled = False
        ask_filled = False
        while tr_idx < n_trades and trades_sorted[tr_idx]["ts"] <= step_end:
            tr = trades_sorted[tr_idx]
            if trades_sorted[tr_idx]["ts"] > step_start:
                price = tr["price"]
                if not bid_filled and price <= bid:
                    q += 1.0
                    cash -= bid
                    bid_filled = True
                    n_bid_fills += 1
                    fills.append({"ts": step_start, "side": "bid", "price": bid, "mid": s})
                elif not ask_filled and price >= ask:
                    q -= 1.0
                    cash += ask
                    ask_filled = True
                    n_ask_fills += 1
                    fills.append({"ts": step_start, "side": "ask", "price": ask, "mid": s})
            tr_idx += 1

        mtm = cash + q * s
        rows.append({
            "local_ts": step_start, "t_elapsed": t_elapsed, "mid": s,
            "reservation_price": r, "bid": bid, "ask": ask, "spread": spread,
            "p_informed": p_informed, "inventory": q, "cash": cash, "mtm_pnl": mtm,
            "bid_filled": bid_filled, "ask_filled": ask_filled,
        })

    final_mid = mids[-1]
    final_mtm = cash + q * final_mid
    inventories = [row["inventory"] for row in rows]

    summary = {
        "label": label,
        "n_steps": len(rows),
        "window_span_sec": times[-1] - times[0],
        "window_start_ts": window_start_ts,
        "window_end_ts": window_end_ts,
        "n_bid_fills": n_bid_fills,
        "n_ask_fills": n_ask_fills,
        "n_fills_total": n_bid_fills + n_ask_fills,
        "final_inventory": q,
        "inventory_min": min(inventories) if inventories else 0.0,
        "inventory_max": max(inventories) if inventories else 0.0,
        "inventory_variance": float(np.var(inventories)) if inventories else 0.0,
        "final_cash": cash,
        "final_mid": final_mid,
        "final_mtm_pnl": final_mtm,
        "spread_mean": (sum(row["spread"] for row in rows) / len(rows)) if rows else None,
        "spread_min": min(row["spread"] for row in rows) if rows else None,
        "spread_max": max(row["spread"] for row in rows) if rows else None,
    }
    return rows, summary, fills, (times, mids)


def compute_realized_spread_captured(fills: list[dict]):
    """Immediate execution markup vs. prevailing mid, per fill -- see
    module docstring. Returns (total, per_fill_list, n_fills)."""
    per_fill = []
    for fill in fills:
        if fill["side"] == "bid":
            captured = fill["mid"] - fill["price"]
        else:
            captured = fill["price"] - fill["mid"]
        per_fill.append({**fill, "spread_captured": captured})
    total = sum(f["spread_captured"] for f in per_fill)
    return total, per_fill, len(per_fill)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--depth", required=True)
    ap.add_argument("--trades", required=True)
    ap.add_argument("--params-json", default="data/processed/estimated_params.json")
    ap.add_argument("--scores-csv", default="data/processed/ml_informedness_scores.csv")
    ap.add_argument("--ml-metrics-json", default="data/processed/ml_informedness_metrics.json")
    ap.add_argument("--out-dir", default="data/processed")
    ap.add_argument("--heuristic-beta", type=float, default=1.0)
    ap.add_argument("--principled-eta", type=float, default=1.0)
    ap.add_argument("--as-cost-horizon-sec", type=float, default=2.0)
    args = ap.parse_args()

    with open(args.params_json) as f:
        p = json.load(f)["params"]
    base_params = ASParams(gamma=p["gamma"], sigma=p["sigma"], kappa=p["kappa"],
                            A=p["A"], T=p["T"])

    with open(args.ml_metrics_json) as f:
        ml_meta = json.load(f)
    feat_meta = ml_meta["feature_meta"]
    train_frac = ml_meta["train_test_split"]["train_frac"]
    expected_adverse_move = feat_meta["expected_adverse_move_given_informed"] or 0.0

    adverse_params = AdverseParams(
        base=base_params,
        heuristic_beta=args.heuristic_beta,
        principled_eta=args.principled_eta,
        expected_adverse_move=expected_adverse_move,
    )

    test_start_ts, test_end_ts, n_test, n_train = get_heldout_window(
        args.depth, args.trades, feat_meta, train_frac,
    )
    print(f"[held-out window] reconstructed from the SAME chronological "
          f"{train_frac:.0%}/{1 - train_frac:.0%} split "
          f"ml_informedness_classifier.py used: train={n_train} rows, "
          f"test={n_test} rows.")
    print(f"[held-out window] local_ts in [{test_start_ts:.3f}, "
          f"{test_end_ts:.3f}] ({test_end_ts - test_start_ts:.1f}s span) -- "
          f"the classifier never trained on any row in this range.")

    p_times, p_values = load_p_informed_series(args.scores_csv)
    p_lookup = make_causal_lookup(p_times, p_values)

    os.makedirs(args.out_dir, exist_ok=True)
    results = {}

    def run_and_report(name, quote_fn, quote_params, use_p):
        lookup = p_lookup if use_p else None
        rows, summary, fills, (times, mids) = run_windowed_backtest(
            args.depth, args.trades, base_params.T,
            quote_fn, quote_params, test_start_ts, test_end_ts,
            p_lookup=lookup, label=name,
        )
        as_cost, per_fill_as_costs, n_valid = compute_adverse_selection_cost(
            fills, times, mids, horizon_sec=args.as_cost_horizon_sec,
        )
        spread_captured_total, per_fill_spread, n_spread = compute_realized_spread_captured(fills)

        summary["adverse_selection_cost_total"] = as_cost
        summary["adverse_selection_cost_n_fills_scored"] = n_valid
        summary["adverse_selection_cost_per_fill"] = (as_cost / n_valid) if n_valid > 0 else None
        summary["realized_spread_captured_total"] = spread_captured_total
        summary["realized_spread_captured_per_fill"] = (
            spread_captured_total / n_spread if n_spread > 0 else None
        )
        summary["net_edge_per_fill"] = (
            summary["realized_spread_captured_per_fill"] - summary["adverse_selection_cost_per_fill"]
            if summary["realized_spread_captured_per_fill"] is not None
            and summary["adverse_selection_cost_per_fill"] is not None
            else None
        )

        series_path = os.path.join(args.out_dir, f"heldout_backtest_series_{name}.csv")
        with open(series_path, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()) if rows else [])
            writer.writeheader()
            writer.writerows(rows)

        fills_path = os.path.join(args.out_dir, f"heldout_backtest_fills_{name}.json")
        with open(fills_path, "w") as f:
            json.dump(per_fill_as_costs, f, indent=2, default=str)

        results[name] = summary
        return summary

    run_and_report("baseline", lambda s, q, t, pr, params: baseline_quote_fn(s, q, t, pr, params),
                    base_params, use_p=False)
    run_and_report("heuristic", lambda s, q, t, pr, params: heuristic_quotes(s, q, t, pr, params),
                    adverse_params, use_p=True)
    run_and_report("principled", lambda s, q, t, pr, params: principled_quotes(s, q, t, pr, params),
                    adverse_params, use_p=True)

    print("\n===== Held-out (genuinely out-of-sample) three-way backtest =====")
    header = f"{'metric':34s}" + "".join(f"{k:>16s}" for k in results.keys())
    print(header)
    metric_keys = [
        "n_fills_total", "n_bid_fills", "n_ask_fills",
        "inventory_min", "inventory_max", "inventory_variance", "final_inventory",
        "spread_mean", "final_mtm_pnl",
        "realized_spread_captured_total", "realized_spread_captured_per_fill",
        "adverse_selection_cost_total", "adverse_selection_cost_n_fills_scored",
        "adverse_selection_cost_per_fill", "net_edge_per_fill",
    ]
    for mk in metric_keys:
        vals = []
        for name in results:
            v = results[name].get(mk)
            if isinstance(v, float):
                vals.append(f"{v:16.4f}")
            else:
                vals.append(f"{str(v):>16s}")
        print(f"{mk:34s}" + "".join(vals))

    out = {
        "note": (
            "Restricted to the chronological test split ml_informedness_classifier.py "
            "never trained on -- see module docstring for why the full-window Part 3 "
            "backtest was contaminated and how this script fixes that."
        ),
        "heldout_window": {
            "test_start_ts": test_start_ts,
            "test_end_ts": test_end_ts,
            "span_sec": test_end_ts - test_start_ts,
            "n_test_rows": n_test,
            "n_train_rows": n_train,
            "train_frac": train_frac,
        },
        "adverse_params": {
            "heuristic_beta": args.heuristic_beta,
            "principled_eta": args.principled_eta,
            "expected_adverse_move": expected_adverse_move,
            "as_cost_horizon_sec": args.as_cost_horizon_sec,
        },
        "results": results,
    }
    comparison_path = os.path.join(args.out_dir, "heldout_backtest_comparison.json")
    with open(comparison_path, "w") as f:
        json.dump(out, f, indent=2, default=str)
    print(f"\nWrote {comparison_path}")


if __name__ == "__main__":
    main()
